### 1. Convert List to 1D Array
#### Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

#### Expected Output:

#### Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [13]:
import numpy as np

my_list = np.array([12.23, 13.32, 100, 36.32])
my_array = my_list
type(my_array)
print(my_array)

[ 12.23  13.32 100.    36.32]


### 2. Create 3x3 Matrix (2?10)
#### Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

#### Expected Output:

##### [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [15]:
import numpy as np

array = np.arange(2, 11)

matrix = array.reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 3. Null Vector (10) & Update Sixth Value

#### Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

#### [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

#### Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [2]:
import numpy as np

# Create a null (zero) vector of size 10
vector = np.zeros(10)

# Update the sixth value (index 6, since indexing starts from 0)
vector[6] = 11

print(vector)


[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### 4. Array from 12 to 38
#### Write a NumPy program to create an array with values ranging from 12 to 38.

#### Expected Output:

#### [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [3]:
my_arr = np.arange(2,38)
print(my_arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37]


### 5. Convert Array to Float Type
#### Write a NumPy program to convert an array to a floating type.

#### Sample output:

#### Original array [1, 2, 3, 4]

In [18]:
my_list = [1, 2, 3, 4]
my_array1 = np.array(my_list)

float_arr = my_array1.astype(float)
float_arr

array([1., 2., 3., 4.])

### 6. Celsius to Fahrenheit Conversion
#### Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

#### Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

#### Expected Output:

#### Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

#### Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

#### Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

#### Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

In [27]:
import numpy as np

# Define Celsius arrays (corrected format)
celsius1 = np.array([0, 12, 45.21, 34, 99.91])
celsius2 = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

# Combine both arrays into one
celsius_combined = np.concatenate((celsius1, celsius2))

# Convert to Fahrenheit
fahrenheit = celsius_combined * 9 / 5 + 32

# Print result
print("Values in Fahrenheit degrees:", np.round(fahrenheit, 2))


Values in Fahrenheit degrees: [ 32.    53.6  113.38  93.2  211.84  -0.    12.    45.21  34.    99.91
  32.  ]


### 7. Append Values to Array (Do self-tudy)
#### Write a NumPy program to append values to the end of an array.

#### Expected Output:

#### Original array: [10, 20, 30]

#### After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [35]:
import numpy as np

arr = np.array([10, 20, 30])
new_arr = np.append(arr, [40, 50, 60, 70, 80, 90])

print(new_arr) 


[10 20 30 40 50 60 70 80 90]


### 8.Array Statistical Functions (Do self-tudy)
### Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [36]:
import numpy as np

# 1. Create a random array with 10 elements
arr = np.random.rand(10)        # values in the range [0, 1)

# 2. Compute statistics
mean_val   = np.mean(arr)
median_val = np.median(arr)
std_val    = np.std(arr)

print("Array:", arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard deviation:", std_val)


Array: [0.81857411 0.74140811 0.20607129 0.86361092 0.74623186 0.54640149
 0.74011263 0.7372882  0.58719899 0.48245946]
Mean: 0.646935706543534
Median: 0.7387004137377366
Standard deviation: 0.18631361468246


### 9. Find min and max
#### Create a 10x10 array with random values and find the minimum and maximum values.

In [39]:
import numpy as np

# 1. Create a 10x10 array with random values
arr = np.random.rand(10, 10)  # values in the range [0, 1)

# 2. Find min and max
min_val = np.min(arr)
max_val = np.max(arr)

# 3. Print results
print("10x10 Random Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


10x10 Random Array:
 [[0.22957696 0.5485383  0.25912266 0.44668111 0.86057105 0.49393125
  0.63048018 0.21559534 0.07480683 0.97218793]
 [0.29659825 0.15914311 0.43721257 0.93529315 0.62246514 0.34007841
  0.02577819 0.22230811 0.43340234 0.19330001]
 [0.86360643 0.98091317 0.11703771 0.63132433 0.46615286 0.4220653
  0.5134285  0.94652269 0.39359246 0.07381023]
 [0.02439404 0.80888753 0.18923773 0.87408778 0.87598573 0.04527877
  0.3858473  0.7234505  0.14915414 0.38285262]
 [0.61993091 0.28402365 0.16936449 0.63561328 0.48956525 0.05680478
  0.52362364 0.1139707  0.66173433 0.10181531]
 [0.47185144 0.73974863 0.40548894 0.27420924 0.62023944 0.96106792
  0.88796302 0.14635682 0.27166853 0.94169784]
 [0.69903643 0.89186015 0.83400826 0.00483223 0.32829136 0.32625458
  0.23428508 0.6776095  0.86661135 0.03312674]
 [0.9987685  0.08029783 0.28135115 0.27346771 0.7497939  0.40368318
  0.30098439 0.95309516 0.8428959  0.23484668]
 [0.25501082 0.21170478 0.65121669 0.77283623 0.78205235 0.8

### 10
Create a 3x3x3 array with random values.

In [38]:
import numpy as np

# Create a 3x3x3 array with random float values in [0, 1)
arr = np.random.rand(3, 3, 3)

print("3x3x3 Random Array:\n", arr)


3x3x3 Random Array:
 [[[0.50976799 0.0492905  0.19406946]
  [0.44637886 0.60488649 0.65321957]
  [0.48783188 0.84782759 0.90126027]]

 [[0.93417928 0.73432738 0.18147586]
  [0.76303812 0.8222483  0.26523189]
  [0.48738949 0.83999904 0.08599726]]

 [[0.18867235 0.80219538 0.61947574]
  [0.7628706  0.64951779 0.95386498]
  [0.8065407  0.3284045  0.01801773]]]
